# Generated by Django 2.2 on 2019-04-10 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190409_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry', to=settings.AUTH_USER_MODEL),
        ),
    ]
